version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: ${CONTAINER_NAME_REDIS}
    env_file:
      - .env
    restart: always
    networks:
      - DevEnvNetwork
    ports:
      - ${HOST}:${REDIS_PORT}:6379

  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_NAME_POSTGRES}
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DATABASE}
    networks:
      - DevEnvNetwork
    ports:
      - ${HOST}:${POSTGRES_PORT}:5432

  sentry:
    build:
      context: docker/dockerfiles
      dockerfile: SentryDocker
    environment:
      - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_POSTGRES_PORT=${POSTGRES_PORT}
      - SENTRY_DB_NAME=${POSTGRES_DEFAULT_DATABASE}
      - SENTRY_DB_USER=${POSTGRES_USER}
      - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}
      - SENTRY_REDIS_HOST=redis
      - SENTRY_REDIS_PORT=${REDIS_PORT}
    container_name: ${CONTAINER_NAME_SENTRY}
    links:
      - redis:redis
      - postgres:postgres
    restart: always
    ports:
      - ${HOST}:${SENTRY_PORT}:9000
    volumes:
      - ./docker/sentry:/var/backups
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - DevEnvNetwork

  sentry-cron:
    image: sentry:latest
    environment:
      - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_POSTGRES_PORT=${POSTGRES_PORT}
      - SENTRY_DB_NAME=${POSTGRES_DEFAULT_DATABASE}
      - SENTRY_DB_USER=${POSTGRES_USER}
      - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}
      - SENTRY_REDIS_HOST=redis
      - SENTRY_REDIS_PORT=${REDIS_PORT}
    container_name: ${CONTAINER_NAME_SENTRY}-cron
    hostname: sentry-cron
    restart: always
    env_file:
      - .env
    depends_on:
      - sentry-redis
      - sentry-postgres
    command: "sentry run cron"
    networks:
      - DevEnvNetwork

  sentry-worker:
    image: sentry:latest
    environment:
      - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_POSTGRES_PORT=${POSTGRES_PORT}
      - SENTRY_DB_NAME=${POSTGRES_DEFAULT_DATABASE}
      - SENTRY_DB_USER=${POSTGRES_USER}
      - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}
      - SENTRY_REDIS_HOST=redis
      - SENTRY_REDIS_PORT=${REDIS_PORT}
    container_name: ${CONTAINER_NAME_SENTRY}-worker
    hostname: sentry-worker
    restart: always
    env_file:
      - .env
    depends_on:
      - sentry-redis
      - sentry-postgres
    command: "sentry run worker"
    networks:
      - DevEnvNetwork

networks:
  DevEnvNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

volumes:
  src:
    name: "src_volume"
