version: '3.8'

services:
  php:
    build:
      context: docker/dockerfiles
      dockerfile: Php8Docker
      args:
        - DOCKER_USERNAME=${USERNAME}
        - DOCKER_UID=${USERID}
    env_file: ['.env']
    volumes:
      - ./src:/var/www
      - ./docker/php-ini:/usr/local/etc/php
      - ./docker/xdebug-ini/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/sampler:/usr/local/etc/sampler
    container_name: ${CONTAINER_NAME_API}
    restart: unless-stopped
    networks:
      - DevEnvNetwork
    tty: true
    stdin_open: true
    links:
      - mysql:database
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    depends_on:
      - nginx
      - mysql

  nginx:
    build:
      context: docker/dockerfiles
      dockerfile: NginxDocker
    container_name: ${CONTAINER_NAME_NGINX}
    networks:
      - DevEnvNetwork
    links:
      - mysql:database
    ports:
      - ${HOST}:80:80
    volumes:
      - ./docker/sites:/etc/nginx/conf.d
      - ./src:/var/www

  mysql:
    build:
      context: docker/dockerfiles
      dockerfile: MysqlDocker
        #args:
        #- MYSQL_USER=${MYSQL_USER}
        #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
        #- MYSQL_DEFAULT_DATABASE=${MYSQL_DEFAULT_DATABASE}
      #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    container_name: ${CONTAINER_NAME_MYSQL}
    networks:
      - DevEnvNetwork
    ports:
      - ${HOST}:3306:3306
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - ./docker/databases:/var/databases
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:
  DevEnvNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        #- subnet: 10.0.0.0/24
        - subnet: 172.29.0.0/16

volumes:
  src:
    name: "src_volume"
