version: '3.8'

services:
  node:
    build:
      context: docker/dockerfiles
      dockerfile: NodeDocker
      args:
        - DOCKER_NODE_VERSION=${DOCKER_NODE_VERSION}
    container_name: ${CONTAINER_NAME_NODE}
    env_file:
      - .env
    networks:
      - DevEnvNetworkExternal
    tty: true
    stdin_open: true
    ports:
      - "${HOST}:3001:3000"
      - "${HOST}:4200:4200"
      - "${HOST}:4201:4201"
    volumes:
      - ./src/Node:/var/app

networks:
  DevEnvNetworkExternal:
    external: true
    name: DevEnvNetwork
