version: '3.8'

services:
  mongo:
    image: mongo
    env_file:
      - ./.env
    container_name: ${CONTAINER_NAME_MONGO}
    restart: always
    ports:
      - ${HOST}:${MONGO_PORT}:27017
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      retries: 30
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"

  mongo-express:
    image: mongo-express
    env_file:
      - ./.env
    container_name: ${CONTAINER_NAME_MONGO_EXPRESS}
    restart: always
    ports:
      - ${HOST}:${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/


networks:
  DevEnvNetworkExternal:
    external: true
    name: DevEnvNetwork

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local
