version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: ${CONTAINER_NAME_GRAFANA}
    env_file:
      - .env
    restart: always
    links:
      - mysql:database
    networks:
      - DevEnvNetwork
    ports:
      - ${HOST}:${GRAFANA_PORT}:3000

networks:
  DevEnvNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

volumes:
  src:
    name: "src_volume"
