textboxes:
  - title: Docker containers stats
    position: [ [ 0, 2 ], [ 79, 10 ] ]
    rate-ms: 1000
    sample: docker stats AlekseyPopov-Dev-Env-api AlekseyPopov-Dev-Env-nginx AlekseyPopov-Dev-Env-mysql --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.PIDs}}"S